name_target: 'JUPITER'
date_obs: "20241214" #vedere nome cartella file

telescope: 'SRT'
num_ch_map: all #numero di canali con cui fare la mappa. Se si vogliono tutti i pixel, scrivere 'all'

paths:
  instrumentation: 'configs/instrument/telescope/SRT.yaml'
  # Location of files (ra, dec, cal) .fits
  # datadir: "data/input/base_test"
  datadir: "/Users/eleonora/Desktop/mistral/OBS/SRT-dicembre/20241214-235843-MISTRAL-3C84_AZ"
  output: "data/output"
  #File of the channels' responsivity
  resp:  #'/home/eleobar/MISTRAL_gen+map-maker/optical_responsivity_new_lowSNR_200mK.pkl'

scan:
  flag_track: True
  beammap_filename: "metadata/chp_offset_rel8_14DEC24_matteo.dat"
  angle_offset: 0
  projection: SIN #'SIN', 'GNOM', "EQ"
  frame: AZEL # 'AZEL' oppure 'RADEC'

  detector_validity:
    upper_threshold: 7
    lower_threshold: 7

map_making:
  pixel_size: 6 arcsec
  npix: [256, 256] # x, y

calibration:
  tau: 0.2
  T_atm: 260
  caldir: "/Users/eleonora/Desktop/mistral/OBS/SRT-dicembre/20241214-170426-MISTRAL-GAIN_CAL/20241214-170426-MISTRAL-GAIN_CAL_002_001.fits"

  method:
    kind: SKYDIP # SKYDIP # or hf or None
    params: {}
   # per hf passo min_freq

filtering:
  #info of box around source to mask during baseline removal and filtering
  radius: 1 arcmin

  debug:
    plot_cm: False
    plot_corr_matrix: False

  mask_without_radius:
    mode: cutted
    offset: 0.1
    sigma: 6
    maxiters: 10


  steps:

    mask_with_radius: 
      - op: remove_baseline
        params:
          deg: 4

      - op: remove_common_mode
        params:
          use_correlation_matrix: True #to have custom common mode for each detector
          return_common_mode: False
      
      # - op: band_pass_filter
      #   params:
      #     btype: 'bandpass'
      #     cuton_freq: 0.05
      #     cutoff_freq: 30
      #     butter_order: 3
  
      # - op: low_pass_filter # il trattino serve per creare la lista steps che dentro contiene una lista per ogni operazione [lowpass_filter, arguments]
      #   params:
      #    btype: 'lowpass'
      #    cutoff_freq: 60
      #    butter_order: 4

    mask_without_radius: []
#     - op: linear_detrend
#        params: { }
      # - op: remove_baseline
      #   params:
      #     deg: 4
      
      # - op: remove_common_mode
      #   params:
      #     use_correlation_matrix: True #to have custom common mode for each detector
      #     return_common_mode: False

    common: []
#      - op: remove_common_mode
#        params:
#          use_correlation_matrix: False
#          return_common_mode: False

#      - op: lowpass_filter # il trattino serve per creare la lista steps che dentro contiene una lista per ogni operazione [lowpass_filter, arguments]
#        params:
#          btype: 'lowpass'
#          cutoff_freq: 60
#          butter_order: 4
#


plot_maps:
  plot_filt: True
  plot_unfilt: False
  plot_counts: False
  plot_std: False

#Save resulting maps in file fits
save_map: True
save_single_pixel_maps: False
