name_target: 'JUPITER'
date_obs: "20241214" #vedere nome cartella file

telescope: 'SRT'
num_ch_map: all #numero di canali con cui fare la mappa. Se si vogliono tutti i pixel, scrivere 'all'

paths:
  instrumentation: 'configs/instrument/telescope/SRT.yaml'
  # Location of files (ra, dec, cal) .fits
  # datadir: "data/input/base_test"
  datadir: "data/input/20241214-204624"
  output: "data/output"
  #File of the channels' responsivity
  resp:  #'/home/eleobar/MISTRAL_gen+map-maker/optical_responsivity_new_lowSNR_200mK.pkl'

scan:
  flag_track: True
  beammap_filename: "metadata/chp_offset_rel8_14DEC24_matteo.dat"
  angle_offset: 0
  projection: SIN #'SIN', 'GNOM', "EQ"
  frame: AZEL # 'AZEL' oppure 'RADEC'

  detector_validity:
    upper_threshold: 7
    lower_threshold: 7

map_making:
  pixel_size: 6 arcsec
  npix: [256, 256] # x, y

calibration:
  tau: 0.2
  T_atm: 260
  caldir: "data/input/20241214-204624/20241214-170426-MISTRAL-GAIN_CAL/20241214-170426-MISTRAL-GAIN_CAL_001_001.fits"

  method:
    kind: None # SKYDIP # or hf or None
    params: {}
   # per hf passo min_freq

filtering:
  # Primary mask choice:
  # - radius > 0 arcsec: build a source-radius mask
  # - radius == 0 arcsec: build a mask using without_radius
  radius: 2 arcsec

  without_radius:
    mode: cut
    offset: 0.1
    sigma: 6
    maxiters: 10

  debug:
    plot_cm: False
    plot_corr_matrix: False

  # User-switchable filtering operations applied after the primary mask is built.
  # Each op must match a function registered in filtering/filters.py.
  steps:
#    - op: remove_baseline
#      params:
#        deg: 4

    - op: linear_detrend
      params: {}

    - op: remove_common_mode
      params:
        use_correlation_matrix: False
        return_common_mode: False

#    - op: low_pass_filter
#      params:
#        btype: 'lowpass'
#        cutoff_freq: 60
#        butter_order: 4
#
#    - op: band_pass_filter
#      params:
#        btype: 'bandpass'
#        cuton_freq: 0
#        cutoff_freq: 60
#        butter_order: 4

plot_maps:
  plot_filt: True
  plot_unfilt: False
  plot_counts: False
  plot_std: False

#Save resulting maps in file fits
save_map: True
save_single_pixel_maps: False
